defaults: &defaults

development:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 192.168.59.103:27017
      database: maison_dev

test:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 192.168.59.103:27017
      database: maison_test

# set these environment variables on your prod server
production:
  <<: *defaults
  sessions:
    default:
      hosts:
        - 127.0.0.1:27017
      database: maison
